version: "3.9"

services:
  web:
    build:
      context: .
    command: gunicorn --bind 0.0.0.0:8000 --pythonpath code django_base.wsgi:application --workers=4
    volumes:
      - static_volume:/code/static
      - media_volume:/code/media
    expose:
      - "8000"
    networks:
      - django-network
  nginx:
    build: nginx
    restart: always
    volumes:
      - static_volume:/code/static
      - media_volume:/code/media
    ports:
      - "80:80"
    depends_on:
      - web
    networks:
      - django-network
networks:
  django-network:
    name: django-network
volumes:
  media_volume:
  static_volume: